/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutVideo: typeof import('@nutui/nutui')['Video']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
